name: Build-deploy-image-docker

on:
  push:
    branches: docker-codigo-fonte


jobs:
  # main:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1 
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: user/app:latest
  #         build-args: |
  #           arg1=value1
  #           arg2=value2
  #     -
  #       name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: docker/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: latest
          tag_with_ref: true
          tag_with_sha: true

